### ISSUE TITLE
Stopped working after recent Manjaro update

### ISSUE THREAD

**Issue by NirmalManoj** [Shatur/optimus-manager-qt#106] opened 2021-10-09 05:38 UTC
**Bug description**

I have been using optimus-manager-qt to select GPU for processing my display. I have dual monitor setup and I was on GPU only mode. After the recent update today morning, my external monitor doesn't get detected anymore. optimus-manager-qt fails to open. The system tray app is also gone.

**Steps to reproduce**

**Expected behavior**

The GUI of optimus-manager should open as usual and detect my external monitor.

**Screenshots**

**Environment**

-   OS:  Manjaro
-   Desktop environment:  KDE
-   Optimus Manager version:   1.4-1
-   Optimus Manager Qt version:  1.6.4-1

**Additional context**

Please let me know if you need any additional information to find out the problem.

**Comment by Shatur** [comment] 2021-10-09 08:10
> After the recent update today morning, my external monitor doesn't get detected anymore. optimus-manager-qt fails to open. The system tray app is also gone.

I think the problem has nothing to do with `optimis-manager-qt`, because this application is just an interface for `optimus-manager`.

> Please let me know if you need any additional information to find out the problem.

Run the application in terminal and show me the log.

**Comment by AdmDevSincro** [comment] 2021-10-28 10:40
I have this after last update

(optimus-manager-qt:7418): Gtk-WARNING **: 05:38:27.524: Theme parsing error: gtk.css:2:103: Failed to import: Error to open the file /usr/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-right/maximized.css: File or directory not exists

**Comment by Shatur** [comment] 2021-10-28 11:09
> (optimus-manager-qt:7418): Gtk-WARNING **: 05:38:27.524: Theme parsing error: gtk.css:2:103: Failed to import: Error to open the file /usr/share/gnome-shell/extensions/unite@hardpixel.eu/styles/buttons-right/maximized.css: File or directory not exists

It's unrelated.

**Comment by Shatur** [comment] 2021-12-04 22:02
Duplicate of #108. The issue on the Optimus Manager side.

**Closed as completed by Shatur** 2021-12-04 22:02 UTC
Labels: bug
